# Essentials Brewfile
# This is the bare minimum needed to begin provisioning a new device.

# YubiKey Manager
brew "ykman"

# GPG
brew "gnupg"

# Git
brew "git"

# GitHub CLI
brew "gh"

# Yet Another Dotfiles Manager (YADM)
brew "yadm"
