# YubiKey Manager
brew "ykman"

# GPG
brew "gnupg"
brew "pinentry-mac"

# Git
brew "git"
brew "git-lfs"
brew "gh"

# LastPass
brew "lastpass-cli"

brew "mas"

# Yubico Authenticator
mas "Yubico Authenticator", id: 1497506650
