#!/bin/bash

source "$HOME/.config/yadm/helpers"

function genSSHKey {
    email=$1
    alg=$2
    keyName=$3

    log "Generating $alg SSH key for $email to $keyName"
    ssh-keygen -t $alg -C "$email" -N "" -f "$keyName"

    eval "$(ssh-agent -s)"

    log "Adding SSH key from $keyName"
    ssh-add "$keyName"
}

if [[ -f "$HOME/.ssh/id_ed25519" ]]; then
    log "Moving $HOME/.ssh/id_ed25519 to $HOME/.ssh/id_ed25519.old"
    mv "$HOME/.ssh/id_ed25519" "$HOME/.ssh/id_ed25519.old"
fi

if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
    log "Moving $HOME/.ssh/id_ed25519.pub to $HOME/.ssh/id_ed25519.pub.old"
    mv "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_ed25519.pub.old"
fi

genSSHKey "$USERNAME@$MACHINE" "ed25519" "$HOME/.ssh/id_ed25519"
