#!/bin/bash

source "$HOME/.config/yadm/helpers"

rm_temps=()

function saveKey {
    local -a title=$1
    local -a key=$2

    if [[ ! -f "$HOME/.ssh/authorized_keys" ]]; then
        log "Creating $HOME/.ssh/authorized_keys"
        touch "$HOME/.ssh/authorized_keys"
    fi

    log "Saving $title to $HOME/.ssh/authorized_keys"
    echo "$key" | tee -a "$HOME/.ssh/authorized_keys"
}

log "Acquiring SSH keys from GitHub"

resp=$(mktemp)
rm_temps=("$resp")

gh api \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /user/keys > "$resp"

save_ifs=$IFS
IFS=$'\n'

for key in $(cat "$resp" | oq -c ".[] | {title, key}"); do
    _oq() {
        echo ${key} | oq -r "${1}"
    }

    saveKey $(_oq ".title") "$(_oq '.key')"
done

log "Cleaning downloaded keys"
IFS=$'\s'
rm -f ${rm_temps[@]}

IFS=$save_ifs
